name: TEST4

on:
  pull_request_review:
    types: [submitted, dismissed]
  pull_request:
    types: [opened] 
            
jobs:
  test4:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
  
    - name: Run
      run: |
        echo "HEllo"    
